//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevYoneticisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class firma_musavir
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public firma_musavir()
        {
            this.musteriler = new HashSet<musteriler>();
            this.yapilacaklar = new HashSet<yapilacaklar>();
            this.proje_surec = new HashSet<proje_surec>();
        }
    
        public int id { get; set; }
        public int flag { get; set; }
        public int vid { get; set; }
        public int sort { get; set; }
        public System.DateTime date { get; set; }
        public string isim { get; set; }
        public string aciklama { get; set; }
        public int proje_sayisi { get; set; }
        public int surec_sayisi { get; set; }
        public int gorev_sayisi { get; set; }
        public int musteri_sayisi { get; set; }
        public int kullanici_sayisi { get; set; }
        public int ekleyen { get; set; }
        public string url { get; set; }
        public string firma_adi { get; set; }
        public string vergi_dairesi { get; set; }
        public string vergi_no { get; set; }
        public string adres { get; set; }
        public int fm_tur { get; set; }
        public int konum_periyot { get; set; }
        public System.DateTime baslangic_tarihi { get; set; }
        public System.DateTime bitis_tarihi { get; set; }
        public string firma_mail { get; set; }
        public string mail_pass { get; set; }
        public string mail_ssl { get; set; }
        public string mail_port { get; set; }
        public string mail_host { get; set; }
        public string musteri_no { get; set; }
        public string sms_header { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<musteriler> musteriler { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yapilacaklar> yapilacaklar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proje_surec> proje_surec { get; set; }
    }
}
