//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevYoneticisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gorevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gorevler()
        {
            this.gorev_dosya = new HashSet<gorev_dosya>();
            this.gorev_loglari = new HashSet<gorev_loglari>();
            this.gorev_musteri = new HashSet<gorev_musteri>();
            this.gorev_proje = new HashSet<gorev_proje>();
            this.yapilacaklar = new HashSet<yapilacaklar>();
            this.kullanici_gorev = new HashSet<kullanici_gorev>();
            this.gorev_baglanti = new HashSet<gorev_baglanti>();
            this.gorev_baglanti1 = new HashSet<gorev_baglanti>();
        }
    
        public int id { get; set; }
        public int flag { get; set; }
        public int vid { get; set; }
        public int sort { get; set; }
        public System.DateTime date { get; set; }
        public int firma_id { get; set; }
        public int ekleyen { get; set; }
        public int yuzde { get; set; }
        public System.DateTime baslangic_tarihi { get; set; }
        public System.DateTime bitis_tarihi { get; set; }
        public string isim { get; set; }
        public string aciklama { get; set; }
        public int durum { get; set; }
        public string url { get; set; }
        public int onaylayan_yetkili { get; set; }
        public System.DateTime tamamlanma_tarihi { get; set; }
        public int gorev_multiply { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorev_dosya> gorev_dosya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorev_loglari> gorev_loglari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorev_musteri> gorev_musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorev_proje> gorev_proje { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yapilacaklar> yapilacaklar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanici_gorev> kullanici_gorev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorev_baglanti> gorev_baglanti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorev_baglanti> gorev_baglanti1 { get; set; }
    }
}
