//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevYoneticisi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vrlfgysdbEntities : DbContext
    {
        public vrlfgysdbEntities()
            : base("name=vrlfgysdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dosyalar> dosyalar { get; set; }
        public virtual DbSet<firma_musavir> firma_musavir { get; set; }
        public virtual DbSet<gorev_dosya> gorev_dosya { get; set; }
        public virtual DbSet<gorev_loglari> gorev_loglari { get; set; }
        public virtual DbSet<gorev_proje> gorev_proje { get; set; }
        public virtual DbSet<kullanici_gorev> kullanici_gorev { get; set; }
        public virtual DbSet<kullanici_musteri> kullanici_musteri { get; set; }
        public virtual DbSet<kullanici_proje> kullanici_proje { get; set; }
        public virtual DbSet<mesajlar> mesajlar { get; set; }
        public virtual DbSet<musteriler> musteriler { get; set; }
        public virtual DbSet<proje_musteri> proje_musteri { get; set; }
        public virtual DbSet<saha_takip> saha_takip { get; set; }
        public virtual DbSet<sistem_bildirimleri> sistem_bildirimleri { get; set; }
        public virtual DbSet<yardim> yardim { get; set; }
        public virtual DbSet<mailler> mailler { get; set; }
        public virtual DbSet<kullanicilar> kullanicilar { get; set; }
        public virtual DbSet<yapilacaklar> yapilacaklar { get; set; }
        public virtual DbSet<gorev_musteri> gorev_musteri { get; set; }
        public virtual DbSet<gorevler> gorevler { get; set; }
        public virtual DbSet<proje_surec> proje_surec { get; set; }
        public virtual DbSet<gorev_baglanti> gorev_baglanti { get; set; }
        public virtual DbSet<smsler> smsler { get; set; }
        public virtual DbSet<sistem_ayarlari> sistem_ayarlari { get; set; }
    }
}
