//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevYoneticisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullanicilar()
        {
            this.firma_musavir = new HashSet<firma_musavir>();
            this.gorev_loglari = new HashSet<gorev_loglari>();
            this.kullanici_gorev = new HashSet<kullanici_gorev>();
            this.kullanici_gorev1 = new HashSet<kullanici_gorev>();
            this.kullanici_musteri = new HashSet<kullanici_musteri>();
            this.kullanici_musteri1 = new HashSet<kullanici_musteri>();
            this.kullanici_proje = new HashSet<kullanici_proje>();
            this.kullanici_proje1 = new HashSet<kullanici_proje>();
            this.mesajlar = new HashSet<mesajlar>();
            this.musteriler = new HashSet<musteriler>();
            this.yapilacaklar = new HashSet<yapilacaklar>();
            this.yardim = new HashSet<yardim>();
            this.mesajlar1 = new HashSet<mesajlar>();
            this.saha_takip = new HashSet<saha_takip>();
            this.gorevler = new HashSet<gorevler>();
            this.gorev_musteri = new HashSet<gorev_musteri>();
            this.dosyalar = new HashSet<dosyalar>();
            this.gorev_dosya = new HashSet<gorev_dosya>();
            this.proje_surec = new HashSet<proje_surec>();
            this.sistem_bildirimleri = new HashSet<sistem_bildirimleri>();
            this.gorev_baglanti = new HashSet<gorev_baglanti>();
            this.smsler = new HashSet<smsler>();
            this.sistem_ayarlari = new HashSet<sistem_ayarlari>();
        }
    
        public int id { get; set; }
        public int flag { get; set; }
        public int vid { get; set; }
        public int sort { get; set; }
        public System.DateTime date { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public int ekleyen { get; set; }
        public int firma_id { get; set; }
        public int kullanici_turu { get; set; }
        public string url { get; set; }
        public string satis_musteri_id { get; set; }
        public string sgk_no { get; set; }
        public string adres { get; set; }
        public string tc_no { get; set; }
        public string vergi_dairesi { get; set; }
        public string vergi_no { get; set; }
        public string reset_guid { get; set; }
        public Nullable<System.DateTime> reset_guidexpiredate { get; set; }
        public int mail_permission { get; set; }
        public int sms_permission { get; set; }
        public string mail_port { get; set; }
        public string mail_ssl { get; set; }
        public string mail_host { get; set; }
        public string mail_psw { get; set; }
        public string username { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<firma_musavir> firma_musavir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorev_loglari> gorev_loglari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanici_gorev> kullanici_gorev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanici_gorev> kullanici_gorev1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanici_musteri> kullanici_musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanici_musteri> kullanici_musteri1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanici_proje> kullanici_proje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanici_proje> kullanici_proje1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesajlar> mesajlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<musteriler> musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yapilacaklar> yapilacaklar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yardim> yardim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesajlar> mesajlar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saha_takip> saha_takip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorevler> gorevler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorev_musteri> gorev_musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dosyalar> dosyalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorev_dosya> gorev_dosya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proje_surec> proje_surec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sistem_bildirimleri> sistem_bildirimleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorev_baglanti> gorev_baglanti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<smsler> smsler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sistem_ayarlari> sistem_ayarlari { get; set; }
    }
}
