//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevYoneticisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mailler
    {
        public int id { get; set; }
        public int flag { get; set; }
        public int vid { get; set; }
        public int sort { get; set; }
        public System.DateTime date { get; set; }
        public int gonderen_id { get; set; }
        public string gonderen_mail { get; set; }
        public string alan_mail { get; set; }
        public string konu { get; set; }
        public string icerik { get; set; }
        public int hedef_id { get; set; }
        public int hedef_tur { get; set; }
        public string url { get; set; }
        public int mail_grup_id { get; set; }
        public int firma_id { get; set; }
    }
}
