//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevYoneticisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesajlar
    {
        public int id { get; set; }
        public int flag { get; set; }
        public int vid { get; set; }
        public int sort { get; set; }
        public System.DateTime date { get; set; }
        public int gonderen_id { get; set; }
        public int alan_id { get; set; }
        public string mesaj { get; set; }
        public int firma_id { get; set; }
        public string url { get; set; }
        public string parent_url { get; set; }
    
        public virtual kullanicilar kullanicilar { get; set; }
        public virtual kullanicilar kullanicilar1 { get; set; }
    }
}
