//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevYoneticisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public musteriler()
        {
            this.kullanici_musteri = new HashSet<kullanici_musteri>();
            this.proje_musteri = new HashSet<proje_musteri>();
            this.gorev_musteri = new HashSet<gorev_musteri>();
        }
    
        public int id { get; set; }
        public int flag { get; set; }
        public int vid { get; set; }
        public int sort { get; set; }
        public System.DateTime date { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string firma { get; set; }
        public string aciklama { get; set; }
        public string url { get; set; }
        public int ekleyen { get; set; }
        public string firma_adi { get; set; }
        public string vergi_dairesi { get; set; }
        public string vergi_no { get; set; }
        public string adres { get; set; }
        public int firma_id { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string gsm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanici_musteri> kullanici_musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proje_musteri> proje_musteri { get; set; }
        public virtual firma_musavir firma_musavir { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gorev_musteri> gorev_musteri { get; set; }
    }
}
