//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevYoneticisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sistem_bildirimleri
    {
        public int id { get; set; }
        public int flag { get; set; }
        public int vid { get; set; }
        public int sort { get; set; }
        public System.DateTime date { get; set; }
        public int bildirim_turu { get; set; }
        public int ilgili_id { get; set; }
        public int kullanici_id { get; set; }
        public int okundu { get; set; }
        public System.DateTime okunma_tarihi { get; set; }
        public string ilgili_url { get; set; }
        public int ekleyen { get; set; }
        public string mesaj { get; set; }
    
        public virtual kullanicilar kullanicilar { get; set; }
    }
}
