//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevYoneticisi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yapilacaklar
    {
        public int id { get; set; }
        public int flag { get; set; }
        public int vid { get; set; }
        public int sort { get; set; }
        public System.DateTime date { get; set; }
        public int gorev_id { get; set; }
        public string isim { get; set; }
        public string aciklama { get; set; }
        public string url { get; set; }
        public int ekleyen { get; set; }
        public int durum { get; set; }
        public int gerceklestiren_id { get; set; }
        public int firma_id { get; set; }
        public System.DateTime tamamlanma_tarihi { get; set; }
    
        public virtual firma_musavir firma_musavir { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
        public virtual gorevler gorevler { get; set; }
    }
}
